| table_name          | constraint_name                           | constraint_type | constraint_details                                                                                                                                                                                                                                                                                                                                                                                               |
| ------------------- | ----------------------------------------- | --------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| articulos           | articulos_pkey                            | PRIMARY KEY     | (id)                                                                                                                                                                                                                                                                                                                                                                                                             |
| articulos           | articulos_storage_path_key                | UNIQUE          | (storage_path)                                                                                                                                                                                                                                                                                                                                                                                                   |
| articulos           | articulos_url_key                         | UNIQUE          | (url)                                                                                                                                                                                                                                                                                                                                                                                                            |
| articulos           | 2200_19482_10_not_null                    | CHECK           | idioma IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                               |
| articulos           | 2200_19482_13_not_null                    | CHECK           | es_opinion IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                           |
| articulos           | 2200_19482_14_not_null                    | CHECK           | es_oficial IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                           |
| articulos           | 2200_19482_18_not_null                    | CHECK           | fecha_recopilacion IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                   |
| articulos           | 2200_19482_1_not_null                     | CHECK           | id IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                                   |
| articulos           | 2200_19482_23_not_null                    | CHECK           | area_geografica IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                      |
| articulos           | 2200_19482_3_not_null                     | CHECK           | storage_path IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                         |
| articulos           | 2200_19482_4_not_null                     | CHECK           | medio IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                                |
| articulos           | 2200_19482_6_not_null                     | CHECK           | tipo_medio IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                           |
| articulos           | 2200_19482_7_not_null                     | CHECK           | titular IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                              |
| articulos           | 2200_19482_8_not_null                     | CHECK           | fecha_publicacion IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                    |
| articulos           | articulos_puntuacion_relevancia_check     | CHECK           | (((puntuacion_relevancia >= 0) AND (puntuacion_relevancia <= 10)))                                                                                                                                                                                                                                                                                                                                               |
| articulos           | check_storage_path_format                 | CHECK           | ((storage_path ~ '^[^/]+/\d{4}/\d{2}/\d{2}/[^/]+\.(html|txt)\.gz$'::text))                                                                                                                                                                                                                                                                                                                                       |
| citas_textuales     | citas_textuales_pkey                      | PRIMARY KEY     | (id)                                                                                                                                                                                                                                                                                                                                                                                                             |
| citas_textuales     | citas_textuales_articulo_id_fkey          | FOREIGN KEY     | REFERENCES articulos(id)                                                                                                                                                                                                                                                                                                                                                                                         |
| citas_textuales     | citas_textuales_documento_id_fkey         | FOREIGN KEY     | REFERENCES documentos_extensos(id)                                                                                                                                                                                                                                                                                                                                                                               |
| citas_textuales     | citas_textuales_entidad_emisora_id_fkey   | FOREIGN KEY     | REFERENCES entidades(id)                                                                                                                                                                                                                                                                                                                                                                                         |
| citas_textuales     | citas_textuales_fragmento_id_fkey         | FOREIGN KEY     | REFERENCES fragmentos_extensos(id)                                                                                                                                                                                                                                                                                                                                                                               |
| citas_textuales     | 2200_19557_10_not_null                    | CHECK           | fecha_ingreso IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                        |
| citas_textuales     | 2200_19557_1_not_null                     | CHECK           | id IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                                   |
| citas_textuales     | 2200_19557_2_not_null                     | CHECK           | cita IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                                 |
| citas_textuales     | 2200_19557_9_not_null                     | CHECK           | relevancia IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                           |
| citas_textuales     | citas_textuales_relevancia_check          | CHECK           | (((relevancia >= 1) AND (relevancia <= 5)))                                                                                                                                                                                                                                                                                                                                                                      |
| contradicciones     | contradicciones_pkey                      | PRIMARY KEY     | (id)                                                                                                                                                                                                                                                                                                                                                                                                             |
| contradicciones     | 2200_19625_1_not_null                     | CHECK           | id IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                                   |
| contradicciones     | 2200_19625_2_not_null                     | CHECK           | hecho_principal_id IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                   |
| contradicciones     | 2200_19625_3_not_null                     | CHECK           | fecha_ocurrencia_principal IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                           |
| contradicciones     | 2200_19625_4_not_null                     | CHECK           | hecho_contradictorio_id IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                              |
| contradicciones     | 2200_19625_5_not_null                     | CHECK           | fecha_ocurrencia_contradictoria IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                      |
| contradicciones     | 2200_19625_6_not_null                     | CHECK           | tipo_contradiccion IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                   |
| contradicciones     | 2200_19625_7_not_null                     | CHECK           | grado_contradiccion IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                  |
| contradicciones     | 2200_19625_9_not_null                     | CHECK           | fecha_deteccion IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                      |
| contradicciones     | check_different_hechos                    | CHECK           | (((hecho_principal_id <> hecho_contradictorio_id) OR (fecha_ocurrencia_principal <> fecha_ocurrencia_contradictoria)))                                                                                                                                                                                                                                                                                           |
| contradicciones     | check_different_hechos                    | CHECK           | (((hecho_principal_id <> hecho_contradictorio_id) OR (fecha_ocurrencia_principal <> fecha_ocurrencia_contradictoria)))                                                                                                                                                                                                                                                                                           |
| contradicciones     | check_different_hechos                    | CHECK           | (((hecho_principal_id <> hecho_contradictorio_id) OR (fecha_ocurrencia_principal <> fecha_ocurrencia_contradictoria)))                                                                                                                                                                                                                                                                                           |
| contradicciones     | check_different_hechos                    | CHECK           | (((hecho_principal_id <> hecho_contradictorio_id) OR (fecha_ocurrencia_principal <> fecha_ocurrencia_contradictoria)))                                                                                                                                                                                                                                                                                           |
| contradicciones     | contradicciones_estado_resolucion_check   | CHECK           | (((estado_resolucion)::text = ANY ((ARRAY['pendiente'::character varying, 'analizada'::character varying, 'resuelta'::character varying, 'ignorada'::character varying])::text[])))                                                                                                                                                                                                                              |
| contradicciones     | contradicciones_grado_contradiccion_check | CHECK           | (((grado_contradiccion >= 1) AND (grado_contradiccion <= 5)))                                                                                                                                                                                                                                                                                                                                                    |
| contradicciones     | contradicciones_tipo_contradiccion_check  | CHECK           | (((tipo_contradiccion)::text = ANY ((ARRAY['fecha'::character varying, 'contenido'::character varying, 'entidades'::character varying, 'ubicacion'::character varying, 'valor'::character varying, 'completa'::character varying])::text[])))                                                                                                                                                                    |
| datos_cuantitativos | datos_cuantitativos_pkey                  | PRIMARY KEY     | (id)                                                                                                                                                                                                                                                                                                                                                                                                             |
| datos_cuantitativos | datos_cuantitativos_articulo_id_fkey      | FOREIGN KEY     | REFERENCES articulos(id)                                                                                                                                                                                                                                                                                                                                                                                         |
| datos_cuantitativos | datos_cuantitativos_documento_id_fkey     | FOREIGN KEY     | REFERENCES documentos_extensos(id)                                                                                                                                                                                                                                                                                                                                                                               |
| datos_cuantitativos | datos_cuantitativos_fragmento_id_fkey     | FOREIGN KEY     | REFERENCES fragmentos_extensos(id)                                                                                                                                                                                                                                                                                                                                                                               |
| datos_cuantitativos | 2200_19597_19_not_null                    | CHECK           | fecha_registro IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                       |
| datos_cuantitativos | 2200_19597_1_not_null                     | CHECK           | id IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                                   |
| datos_cuantitativos | 2200_19597_4_not_null                     | CHECK           | indicador IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                            |
| datos_cuantitativos | 2200_19597_5_not_null                     | CHECK           | categoria IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                            |
| datos_cuantitativos | 2200_19597_6_not_null                     | CHECK           | valor_numerico IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                       |
| datos_cuantitativos | 2200_19597_7_not_null                     | CHECK           | unidad IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                               |
| datos_cuantitativos | 2200_19597_8_not_null                     | CHECK           | ambito_geografico IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                    |
| datos_cuantitativos | datos_cuantitativos_categoria_check       | CHECK           | (((categoria)::text = ANY ((ARRAY['económico'::character varying, 'demográfico'::character varying, 'electoral'::character varying, 'social'::character varying, 'presupuestario'::character varying, 'sanitario'::character varying, 'ambiental'::character varying, 'conflicto'::character varying, 'otro'::character varying])::text[])))                                                                     |
| datos_cuantitativos | datos_cuantitativos_tendencia_check       | CHECK           | (((tendencia)::text = ANY ((ARRAY['aumento'::character varying, 'disminución'::character varying, 'estable'::character varying, NULL::character varying])::text[])))                                                                                                                                                                                                                                             |
| datos_cuantitativos | datos_cuantitativos_tipo_periodo_check    | CHECK           | (((tipo_periodo)::text = ANY ((ARRAY['anual'::character varying, 'trimestral'::character varying, 'mensual'::character varying, 'semanal'::character varying, 'diario'::character varying, 'puntual'::character varying, 'acumulado'::character varying, NULL::character varying])::text[])))                                                                                                                    |
| entidad_relacion    | entidad_relacion_pkey                     | PRIMARY KEY     | (entidad_origen_id, tipo_relacion, entidad_destino_id)                                                                                                                                                                                                                                                                                                                                                           |
| entidad_relacion    | entidad_relacion_pkey                     | PRIMARY KEY     | (entidad_origen_id, entidad_destino_id, tipo_relacion)                                                                                                                                                                                                                                                                                                                                                           |
| entidad_relacion    | entidad_relacion_pkey                     | PRIMARY KEY     | (tipo_relacion, entidad_origen_id, entidad_destino_id)                                                                                                                                                                                                                                                                                                                                                           |
| entidad_relacion    | entidad_relacion_entidad_destino_id_fkey  | FOREIGN KEY     | REFERENCES entidades(id)                                                                                                                                                                                                                                                                                                                                                                                         |
| entidad_relacion    | entidad_relacion_entidad_origen_id_fkey   | FOREIGN KEY     | REFERENCES entidades(id)                                                                                                                                                                                                                                                                                                                                                                                         |
| entidad_relacion    | 2200_20106_1_not_null                     | CHECK           | entidad_origen_id IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                    |
| entidad_relacion    | 2200_20106_2_not_null                     | CHECK           | entidad_destino_id IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                   |
| entidad_relacion    | 2200_20106_3_not_null                     | CHECK           | tipo_relacion IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                        |
| entidad_relacion    | 2200_20106_7_not_null                     | CHECK           | fuerza_relacion IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                      |
| entidad_relacion    | check_different_related_entities          | CHECK           | ((entidad_origen_id <> entidad_destino_id))                                                                                                                                                                                                                                                                                                                                                                      |
| entidad_relacion    | check_different_related_entities          | CHECK           | ((entidad_origen_id <> entidad_destino_id))                                                                                                                                                                                                                                                                                                                                                                      |
| entidad_relacion    | entidad_relacion_fuerza_relacion_check    | CHECK           | (((fuerza_relacion >= 1) AND (fuerza_relacion <= 10)))                                                                                                                                                                                                                                                                                                                                                           |
| entidad_relacion    | entidad_relacion_tipo_relacion_check      | CHECK           | (((tipo_relacion)::text = ANY ((ARRAY['miembro_de'::character varying, 'subsidiaria_de'::character varying, 'aliado_con'::character varying, 'opositor_a'::character varying, 'sucesor_de'::character varying, 'predecesor_de'::character varying, 'casado_con'::character varying, 'familiar_de'::character varying, 'empleado_de'::character varying])::text[])))                                              |
| entidades           | entidades_pkey                            | PRIMARY KEY     | (id)                                                                                                                                                                                                                                                                                                                                                                                                             |
| entidades           | entidades_fusionada_en_id_fkey            | FOREIGN KEY     | REFERENCES entidades(id)                                                                                                                                                                                                                                                                                                                                                                                         |
| entidades           | 2200_19466_1_not_null                     | CHECK           | id IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                                   |
| entidades           | 2200_19466_2_not_null                     | CHECK           | nombre IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                               |
| entidades           | 2200_19466_3_not_null                     | CHECK           | tipo IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                                 |
| entidades           | 2200_19466_9_not_null                     | CHECK           | relevancia IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                           |
| entidades           | entidades_relevancia_check                | CHECK           | (((relevancia >= 1) AND (relevancia <= 10)))                                                                                                                                                                                                                                                                                                                                                                     |
| hecho_articulo      | hecho_articulo_pkey                       | PRIMARY KEY     | (hecho_id, fecha_ocurrencia_hecho, articulo_id)                                                                                                                                                                                                                                                                                                                                                                  |
| hecho_articulo      | hecho_articulo_pkey                       | PRIMARY KEY     | (fecha_ocurrencia_hecho, articulo_id, hecho_id)                                                                                                                                                                                                                                                                                                                                                                  |
| hecho_articulo      | hecho_articulo_pkey                       | PRIMARY KEY     | (fecha_ocurrencia_hecho, articulo_id, hecho_id)                                                                                                                                                                                                                                                                                                                                                                  |
| hecho_articulo      | hecho_articulo_articulo_id_fkey           | FOREIGN KEY     | REFERENCES articulos(id)                                                                                                                                                                                                                                                                                                                                                                                         |
| hecho_articulo      | 2200_20065_1_not_null                     | CHECK           | hecho_id IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                             |
| hecho_articulo      | 2200_20065_2_not_null                     | CHECK           | fecha_ocurrencia_hecho IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                               |
| hecho_articulo      | 2200_20065_3_not_null                     | CHECK           | articulo_id IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                          |
| hecho_articulo      | 2200_20065_6_not_null                     | CHECK           | es_fuente_primaria IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                   |
| hecho_articulo      | 2200_20065_7_not_null                     | CHECK           | confirma_hecho IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                       |
| hecho_entidad       | hecho_entidad_pkey                        | PRIMARY KEY     | (tipo_relacion, entidad_id, fecha_ocurrencia_hecho, hecho_id)                                                                                                                                                                                                                                                                                                                                                    |
| hecho_entidad       | hecho_entidad_pkey                        | PRIMARY KEY     | (tipo_relacion, hecho_id, fecha_ocurrencia_hecho, entidad_id)                                                                                                                                                                                                                                                                                                                                                    |
| hecho_entidad       | hecho_entidad_pkey                        | PRIMARY KEY     | (entidad_id, fecha_ocurrencia_hecho, tipo_relacion, hecho_id)                                                                                                                                                                                                                                                                                                                                                    |
| hecho_entidad       | hecho_entidad_pkey                        | PRIMARY KEY     | (entidad_id, tipo_relacion, hecho_id, fecha_ocurrencia_hecho)                                                                                                                                                                                                                                                                                                                                                    |
| hecho_entidad       | hecho_entidad_entidad_id_fkey             | FOREIGN KEY     | REFERENCES entidades(id)                                                                                                                                                                                                                                                                                                                                                                                         |
| hecho_entidad       | 2200_20050_1_not_null                     | CHECK           | hecho_id IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                             |
| hecho_entidad       | 2200_20050_2_not_null                     | CHECK           | fecha_ocurrencia_hecho IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                               |
| hecho_entidad       | 2200_20050_3_not_null                     | CHECK           | entidad_id IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                           |
| hecho_entidad       | 2200_20050_4_not_null                     | CHECK           | tipo_relacion IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                        |
| hecho_entidad       | 2200_20050_5_not_null                     | CHECK           | relevancia_en_hecho IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                  |
| hecho_entidad       | hecho_entidad_relevancia_en_hecho_check   | CHECK           | (((relevancia_en_hecho >= 1) AND (relevancia_en_hecho <= 10)))                                                                                                                                                                                                                                                                                                                                                   |
| hecho_entidad       | hecho_entidad_tipo_relacion_check         | CHECK           | (((tipo_relacion)::text = ANY ((ARRAY['protagonista'::character varying, 'mencionado'::character varying, 'afectado'::character varying, 'declarante'::character varying, 'ubicacion'::character varying, 'contexto'::character varying, 'victima'::character varying, 'agresor'::character varying, 'organizador'::character varying, 'participante'::character varying, 'otro'::character varying])::text[]))) |
| hecho_relacionado   | hecho_relacionado_pkey                    | PRIMARY KEY     | (hecho_destino_id, fecha_ocurrencia_destino, hecho_origen_id, fecha_ocurrencia_origen, tipo_relacion)                                                                                                                                                                                                                                                                                                            |
| hecho_relacionado   | hecho_relacionado_pkey                    | PRIMARY KEY     | (hecho_origen_id, fecha_ocurrencia_destino, tipo_relacion, hecho_destino_id, fecha_ocurrencia_origen)                                                                                                                                                                                                                                                                                                            |
| hecho_relacionado   | hecho_relacionado_pkey                    | PRIMARY KEY     | (hecho_destino_id, fecha_ocurrencia_origen, hecho_origen_id, fecha_ocurrencia_destino, tipo_relacion)                                                                                                                                                                                                                                                                                                            |
| hecho_relacionado   | hecho_relacionado_pkey                    | PRIMARY KEY     | (fecha_ocurrencia_destino, fecha_ocurrencia_origen, hecho_destino_id, tipo_relacion, hecho_origen_id)                                                                                                                                                                                                                                                                                                            |
| hecho_relacionado   | hecho_relacionado_pkey                    | PRIMARY KEY     | (fecha_ocurrencia_origen, hecho_destino_id, tipo_relacion, hecho_origen_id, fecha_ocurrencia_destino)                                                                                                                                                                                                                                                                                                            |
| hecho_relacionado   | 2200_20079_1_not_null                     | CHECK           | hecho_origen_id IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                      |
| hecho_relacionado   | 2200_20079_2_not_null                     | CHECK           | fecha_ocurrencia_origen IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                              |
| hecho_relacionado   | 2200_20079_3_not_null                     | CHECK           | hecho_destino_id IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                     |
| hecho_relacionado   | 2200_20079_4_not_null                     | CHECK           | fecha_ocurrencia_destino IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                             |
| hecho_relacionado   | 2200_20079_5_not_null                     | CHECK           | tipo_relacion IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                        |
| hecho_relacionado   | 2200_20079_6_not_null                     | CHECK           | fuerza_relacion IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                      |
| hecho_relacionado   | check_different_related_hechos            | CHECK           | (((hecho_origen_id <> hecho_destino_id) OR (fecha_ocurrencia_origen <> fecha_ocurrencia_destino)))                                                                                                                                                                                                                                                                                                               |
| hecho_relacionado   | check_different_related_hechos            | CHECK           | (((hecho_origen_id <> hecho_destino_id) OR (fecha_ocurrencia_origen <> fecha_ocurrencia_destino)))                                                                                                                                                                                                                                                                                                               |
| hecho_relacionado   | check_different_related_hechos            | CHECK           | (((hecho_origen_id <> hecho_destino_id) OR (fecha_ocurrencia_origen <> fecha_ocurrencia_destino)))                                                                                                                                                                                                                                                                                                               |
| hecho_relacionado   | check_different_related_hechos            | CHECK           | (((hecho_origen_id <> hecho_destino_id) OR (fecha_ocurrencia_origen <> fecha_ocurrencia_destino)))                                                                                                                                                                                                                                                                                                               |
| hecho_relacionado   | hecho_relacionado_fuerza_relacion_check   | CHECK           | (((fuerza_relacion >= 1) AND (fuerza_relacion <= 10)))                                                                                                                                                                                                                                                                                                                                                           |
| hecho_relacionado   | hecho_relacionado_tipo_relacion_check     | CHECK           | (((tipo_relacion)::text = ANY ((ARRAY['causa'::character varying, 'consecuencia'::character varying, 'contexto_historico'::character varying, 'respuesta_a'::character varying, 'aclaracion_de'::character varying, 'version_alternativa'::character varying, 'seguimiento_de'::character varying])::text[])))                                                                                                   |
| hechos              | hechos_documento_id_fkey                  | FOREIGN KEY     | REFERENCES documentos_extensos(id)                                                                                                                                                                                                                                                                                                                                                                               |
| hechos              | hechos_fragmento_id_fkey                  | FOREIGN KEY     | REFERENCES fragmentos_extensos(id)                                                                                                                                                                                                                                                                                                                                                                               |
| hechos              | 2200_19734_15_not_null                    | CHECK           | fecha_ingreso IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                        |
| hechos              | 2200_19734_1_not_null                     | CHECK           | id IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                                   |
| hechos              | 2200_19734_2_not_null                     | CHECK           | contenido IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                            |
| hechos              | 2200_19734_3_not_null                     | CHECK           | fecha_ocurrencia IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                     |
| hechos              | 2200_19734_4_not_null                     | CHECK           | precision_temporal IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                   |
| hechos              | 2200_19734_5_not_null                     | CHECK           | importancia IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                          |
| hechos              | 2200_19734_6_not_null                     | CHECK           | tipo_hecho IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                           |
| hechos              | 2200_19734_7_not_null                     | CHECK           | pais IS NOT NULL                                                                                                                                                                                                                                                                                                                                                                                                 |
| hechos              | hechos_confiabilidad_programacion_check   | CHECK           | (((confiabilidad_programacion >= 1) AND (confiabilidad_programacion <= 5)))                                                                                                                                                                                                                                                                                                                                      |
| hechos              | hechos_confiabilidad_programacion_check   | CHECK           | (((confiabilidad_programacion >= 1) AND (confiabilidad_programacion <= 5)))                                                                                                                                                                                                                                                                                                                                      |
| hechos              | hechos_confiabilidad_programacion_check   | CHECK           | (((confiabilidad_programacion >= 1) AND (confiabilidad_programacion <= 5)))                                                                                                                                                                                                                                                                                                                                      |
| hechos              | hechos_confiabilidad_programacion_check   | CHECK           | (((confiabilidad_programacion >= 1) AND (confiabilidad_programacion <= 5)))                                                                                                                                                                                                                                                                                                                                      |
| hechos              | hechos_confiabilidad_programacion_check   | CHECK           | (((confiabilidad_programacion >= 1) AND (confiabilidad_programacion <= 5)))                                                                                                                                                                                                                                                                                                                                      |
| hechos              | hechos_confiabilidad_programacion_check   | CHECK           | (((confiabilidad_programacion >= 1) AND (confiabilidad_programacion <= 5)))                                                                                                                                                                                                                                                                                                                                      |
| hechos              | hechos_confiabilidad_programacion_check   | CHECK           | (((confiabilidad_programacion >= 1) AND (confiabilidad_programacion <= 5)))                                                                                                                                                                                                                                                                                                                                      |
| hechos              | hechos_confiabilidad_programacion_check   | CHECK           | (((confiabilidad_programacion >= 1) AND (confiabilidad_programacion <= 5)))                                                                                                                                                                                                                                                                                                                                      |
| hechos              | hechos_confiabilidad_programacion_check   | CHECK           | (((confiabilidad_programacion >= 1) AND (confiabilidad_programacion <= 5)))                                                                                                                                                                                                                                                                                                                                      |
| hechos              | hechos_confiabilidad_programacion_check   | CHECK           | (((confiabilidad_programacion >= 1) AND (confiabilidad_programacion <= 5)))                                                                                                                                                                                                                                                                                                                                      |
| hechos              | hechos_consenso_fuentes_check             | CHECK           | (((consenso_fuentes)::text = ANY ((ARRAY['pendiente_analisis_fuentes'::character varying, 'confirmado_multiples_fuentes'::character varying, 'sin_confirmacion_suficiente_fuentes'::character varying, 'en_disputa_por_hechos_contradictorios'::character varying])::text[])))                                                                                                                                   |
| hechos              | hechos_consenso_fuentes_check             | CHECK           | (((consenso_fuentes)::text = ANY ((ARRAY['pendiente_analisis_fuentes'::character varying, 'confirmado_multiples_fuentes'::character varying, 'sin_confirmacion_suficiente_fuentes'::character varying, 'en_disputa_por_hechos_contradictorios'::character varying])::text[])))                                                                                                                                   |
| hechos              | hechos_consenso_fuentes_check             | CHECK           | (((consenso_fuentes)::text = ANY ((ARRAY['pendiente_analisis_fuentes'::character varying, 'confirmado_multiples_fuentes'::character varying, 'sin_confirmacion_suficiente_fuentes'::character varying, 'en_disputa_por_hechos_contradictorios'::character varying])::text[])))                                                                                                                                   |
| hechos              | hechos_consenso_fuentes_check             | CHECK           | (((consenso_fuentes)::text = ANY ((ARRAY['pendiente_analisis_fuentes'::character varying, 'confirmado_multiples_fuentes'::character varying, 'sin_confirmacion_suficiente_fuentes'::character varying, 'en_disputa_por_hechos_contradictorios'::character varying])::text[])))                                                                                                                                   |
| hechos              | hechos_consenso_fuentes_check             | CHECK           | (((consenso_fuentes)::text = ANY ((ARRAY['pendiente_analisis_fuentes'::character varying, 'confirmado_multiples_fuentes'::character varying, 'sin_confirmacion_suficiente_fuentes'::character varying, 'en_disputa_por_hechos_contradictorios'::character varying])::text[])))                                                                                                                                   |
| hechos              | hechos_consenso_fuentes_check             | CHECK           | (((consenso_fuentes)::text = ANY ((ARRAY['pendiente_analisis_fuentes'::character varying, 'confirmado_multiples_fuentes'::character varying, 'sin_confirmacion_suficiente_fuentes'::character varying, 'en_disputa_por_hechos_contradictorios'::character varying])::text[])))                                                                                                                                   |
| hechos              | hechos_consenso_fuentes_check             | CHECK           | (((consenso_fuentes)::text = ANY ((ARRAY['pendiente_analisis_fuentes'::character varying, 'confirmado_multiples_fuentes'::character varying, 'sin_confirmacion_suficiente_fuentes'::character varying, 'en_disputa_por_hechos_contradictorios'::character varying])::text[])))                                                                                                                                   |
| hechos              | hechos_consenso_fuentes_check             | CHECK           | (((consenso_fuentes)::text = ANY ((ARRAY['pendiente_analisis_fuentes'::character varying, 'confirmado_multiples_fuentes'::character varying, 'sin_confirmacion_suficiente_fuentes'::character varying, 'en_disputa_por_hechos_contradictorios'::character varying])::text[])))                                                                                                                                   |
| hechos              | hechos_consenso_fuentes_check             | CHECK           | (((consenso_fuentes)::text = ANY ((ARRAY['pendiente_analisis_fuentes'::character varying, 'confirmado_multiples_fuentes'::character varying, 'sin_confirmacion_suficiente_fuentes'::character varying, 'en_disputa_por_hechos_contradictorios'::character varying])::text[])))                                                                                                                                   |
| hechos              | hechos_consenso_fuentes_check             | CHECK           | (((consenso_fuentes)::text = ANY ((ARRAY['pendiente_analisis_fuentes'::character varying, 'confirmado_multiples_fuentes'::character varying, 'sin_confirmacion_suficiente_fuentes'::character varying, 'en_disputa_por_hechos_contradictorios'::character varying])::text[])))                                                                                                                                   |
| hechos              | hechos_estado_programacion_check          | CHECK           | (((estado_programacion)::text = ANY ((ARRAY['programado'::character varying, 'confirmado'::character varying, 'cancelado'::character varying, 'modificado'::character varying, 'realizado'::character varying, NULL::character varying])::text[])))                                                                                                                                                              |
| hechos              | hechos_estado_programacion_check          | CHECK           | (((estado_programacion)::text = ANY ((ARRAY['programado'::character varying, 'confirmado'::character varying, 'cancelado'::character varying, 'modificado'::character varying, 'realizado'::character varying, NULL::character varying])::text[])))                                                                                                                                                              |
| hechos              | hechos_estado_programacion_check          | CHECK           | (((estado_programacion)::text = ANY ((ARRAY['programado'::character varying, 'confirmado'::character varying, 'cancelado'::character varying, 'modificado'::character varying, 'realizado'::character varying, NULL::character varying])::text[])))                                                                                                                                                              |
| hechos              | hechos_estado_programacion_check          | CHECK           | (((estado_programacion)::text = ANY ((ARRAY['programado'::character varying, 'confirmado'::character varying, 'cancelado'::character varying, 'modificado'::character varying, 'realizado'::character varying, NULL::character varying])::text[])))                                                                                                                                                              |
| hechos              | hechos_estado_programacion_check          | CHECK           | (((estado_programacion)::text = ANY ((ARRAY['programado'::character varying, 'confirmado'::character varying, 'cancelado'::character varying, 'modificado'::character varying, 'realizado'::character varying, NULL::character varying])::text[])))                                                                                                                                                              |
| hechos              | hechos_estado_programacion_check          | CHECK           | (((estado_programacion)::text = ANY ((ARRAY['programado'::character varying, 'confirmado'::character varying, 'cancelado'::character varying, 'modificado'::character varying, 'realizado'::character varying, NULL::character varying])::text[])))                                                                                                                                                              |
| hechos              | hechos_estado_programacion_check          | CHECK           | (((estado_programacion)::text = ANY ((ARRAY['programado'::character varying, 'confirmado'::character varying, 'cancelado'::character varying, 'modificado'::character varying, 'realizado'::character varying, NULL::character varying])::text[])))                                                                                                                                                              |
| hechos              | hechos_estado_programacion_check          | CHECK           | (((estado_programacion)::text = ANY ((ARRAY['programado'::character varying, 'confirmado'::character varying, 'cancelado'::character varying, 'modificado'::character varying, 'realizado'::character varying, NULL::character varying])::text[])))                                                                                                                                                              |
| hechos              | hechos_estado_programacion_check          | CHECK           | (((estado_programacion)::text = ANY ((ARRAY['programado'::character varying, 'confirmado'::character varying, 'cancelado'::character varying, 'modificado'::character varying, 'realizado'::character varying, NULL::character varying])::text[])))                                                                                                                                                              |
| hechos              | hechos_estado_programacion_check          | CHECK           | (((estado_programacion)::text = ANY ((ARRAY['programado'::character varying, 'confirmado'::character varying, 'cancelado'::character varying, 'modificado'::character varying, 'realizado'::character varying, NULL::character varying])::text[])))                                                                                                                                                              |
| hechos              | hechos_evaluacion_editorial_check         | CHECK           | (((evaluacion_editorial)::text = ANY ((ARRAY['pendiente_revision_editorial'::character varying, 'verificado_ok_editorial'::character varying, 'declarado_falso_editorial'::character varying])::text[])))                                                                                                                                                                                                        |
| hechos              | hechos_evaluacion_editorial_check         | CHECK           | (((evaluacion_editorial)::text = ANY ((ARRAY['pendiente_revision_editorial'::character varying, 'verificado_ok_editorial'::character varying, 'declarado_falso_editorial'::character varying])::text[])))                                                                                                                                                                                                        |
| hechos              | hechos_evaluacion_editorial_check         | CHECK           | (((evaluacion_editorial)::text = ANY ((ARRAY['pendiente_revision_editorial'::character varying, 'verificado_ok_editorial'::character varying, 'declarado_falso_editorial'::character varying])::text[])))                                                                                                                                                                                                        |
| hechos              | hechos_evaluacion_editorial_check         | CHECK           | (((evaluacion_editorial)::text = ANY ((ARRAY['pendiente_revision_editorial'::character varying, 'verificado_ok_editorial'::character varying, 'declarado_falso_editorial'::character varying])::text[])))                                                                                                                                                                                                        |
| hechos              | hechos_evaluacion_editorial_check         | CHECK           | (((evaluacion_editorial)::text = ANY ((ARRAY['pendiente_revision_editorial'::character varying, 'verificado_ok_editorial'::character varying, 'declarado_falso_editorial'::character varying])::text[])))                                                                                                                                                                                                        |
| hechos              | hechos_evaluacion_editorial_check         | CHECK           | (((evaluacion_editorial)::text = ANY ((ARRAY['pendiente_revision_editorial'::character varying, 'verificado_ok_editorial'::character varying, 'declarado_falso_editorial'::character varying])::text[])))                                                                                                                                                                                                        |
| hechos              | hechos_evaluacion_editorial_check         | CHECK           | (((evaluacion_editorial)::text = ANY ((ARRAY['pendiente_revision_editorial'::character varying, 'verificado_ok_editorial'::character varying, 'declarado_falso_editorial'::character varying])::text[])))                                                                                                                                                                                                        |
| hechos              | hechos_evaluacion_editorial_check         | CHECK           | (((evaluacion_editorial)::text = ANY ((ARRAY['pendiente_revision_editorial'::character varying, 'verificado_ok_editorial'::character varying, 'declarado_falso_editorial'::character varying])::text[])))                                                                                                                                                                                                        |
| hechos              | hechos_evaluacion_editorial_check         | CHECK           | (((evaluacion_editorial)::text = ANY ((ARRAY['pendiente_revision_editorial'::character varying, 'verificado_ok_editorial'::character varying, 'declarado_falso_editorial'::character varying])::text[])))                                                                                                                                                                                                        |
| hechos              | hechos_evaluacion_editorial_check         | CHECK           | (((evaluacion_editorial)::text = ANY ((ARRAY['pendiente_revision_editorial'::character varying, 'verificado_ok_editorial'::character varying, 'declarado_falso_editorial'::character varying])::text[])))                                                                                                                                                                                                        |
| hechos              | hechos_importancia_check                  | CHECK           | (((importancia >= 1) AND (importancia <= 10)))                                                                                                                                                                                                                                                                                                                                                                   |
| hechos              | hechos_importancia_check                  | CHECK           | (((importancia >= 1) AND (importancia <= 10)))                                                                                                                                                                                                                                                                                                                                                                   |
| hechos              | hechos_importancia_check                  | CHECK           | (((importancia >= 1) AND (importancia <= 10)))                                                                                                                                                                                                                                                                                                                                                                   |
| hechos              | hechos_importancia_check                  | CHECK           | (((importancia >= 1) AND (importancia <= 10)))                                                                                                                                                                                                                                                                                                                                                                   |
| hechos              | hechos_importancia_check                  | CHECK           | (((importancia >= 1) AND (importancia <= 10)))                                                                                                                                                                                                                                                                                                                                                                   |
| hechos              | hechos_importancia_check                  | CHECK           | (((importancia >= 1) AND (importancia <= 10)))                                                                                                                                                                                                                                                                                                                                                                   |
| hechos              | hechos_importancia_check                  | CHECK           | (((importancia >= 1) AND (importancia <= 10)))                                                                                                                                                                                                                                                                                                                                                                   |
| hechos              | hechos_importancia_check                  | CHECK           | (((importancia >= 1) AND (importancia <= 10)))                                                                                                                                                                                                                                                                                                                                                                   |
| hechos              | hechos_importancia_check                  | CHECK           | (((importancia >= 1) AND (importancia <= 10)))                                                                                                                                                                                                                                                                                                                                                                   |
| hechos              | hechos_importancia_check                  | CHECK           | (((importancia >= 1) AND (importancia <= 10)))                                                                                                                                                                                                                                                                                                                                                                   |
| hechos              | hechos_precision_temporal_check           | CHECK           | (((precision_temporal)::text = ANY ((ARRAY['exacta'::character varying, 'dia'::character varying, 'semana'::character varying, 'mes'::character varying, 'trimestre'::character varying, 'año'::character varying, 'decada'::character varying, 'periodo'::character varying, 'desconocido'::character varying])::text[])))                                                                                      |
| hechos              | hechos_precision_temporal_check           | CHECK           | (((precision_temporal)::text = ANY ((ARRAY['exacta'::character varying, 'dia'::character varying, 'semana'::character varying, 'mes'::character varying, 'trimestre'::character varying, 'año'::character varying, 'decada'::character varying, 'periodo'::character varying, 'desconocido'::character varying])::text[])))                                                                                      |
| hechos              | hechos_precision_temporal_check           | CHECK           | (((precision_temporal)::text = ANY ((ARRAY['exacta'::character varying, 'dia'::character varying, 'semana'::character varying, 'mes'::character varying, 'trimestre'::character varying, 'año'::character varying, 'decada'::character varying, 'periodo'::character varying, 'desconocido'::character varying])::text[])))                                                                                      |
| hechos              | hechos_precision_temporal_check           | CHECK           | (((precision_temporal)::text = ANY ((ARRAY['exacta'::character varying, 'dia'::character varying, 'semana'::character varying, 'mes'::character varying, 'trimestre'::character varying, 'año'::character varying, 'decada'::character varying, 'periodo'::character varying, 'desconocido'::character varying])::text[])))                                                                                      |
| hechos              | hechos_precision_temporal_check           | CHECK           | (((precision_temporal)::text = ANY ((ARRAY['exacta'::character varying, 'dia'::character varying, 'semana'::character varying, 'mes'::character varying, 'trimestre'::character varying, 'año'::character varying, 'decada'::character varying, 'periodo'::character varying, 'desconocido'::character varying])::text[])))                                                                                      |
| hechos              | hechos_precision_temporal_check           | CHECK           | (((precision_temporal)::text = ANY ((ARRAY['exacta'::character varying, 'dia'::character varying, 'semana'::character varying, 'mes'::character varying, 'trimestre'::character varying, 'año'::character varying, 'decada'::character varying, 'periodo'::character varying, 'desconocido'::character varying])::text[])))                                                                                      |
| hechos              | hechos_precision_temporal_check           | CHECK           | (((precision_temporal)::text = ANY ((ARRAY['exacta'::character varying, 'dia'::character varying, 'semana'::character varying, 'mes'::character varying, 'trimestre'::character varying, 'año'::character varying, 'decada'::character varying, 'periodo'::character varying, 'desconocido'::character varying])::text[])))                                                                                      |
| hechos              | hechos_precision_temporal_check           | CHECK           | (((precision_temporal)::text = ANY ((ARRAY['exacta'::character varying, 'dia'::character varying, 'semana'::character varying, 'mes'::character varying, 'trimestre'::character varying, 'año'::character varying, 'decada'::character varying, 'periodo'::character varying, 'desconocido'::character varying])::text[])))                                                                                      |
| hechos              | hechos_precision_temporal_check           | CHECK           | (((precision_temporal)::text = ANY ((ARRAY['exacta'::character varying, 'dia'::character varying, 'semana'::character varying, 'mes'::character varying, 'trimestre'::character varying, 'año'::character varying, 'decada'::character varying, 'periodo'::character varying, 'desconocido'::character varying])::text[])))                                                                                      |
| hechos              | hechos_precision_temporal_check           | CHECK           | (((precision_temporal)::text = ANY ((ARRAY['exacta'::character varying, 'dia'::character varying, 'semana'::character varying, 'mes'::character varying, 'trimestre'::character varying, 'año'::character varying, 'decada'::character varying, 'periodo'::character varying, 'desconocido'::character varying])::text[])))                                                                                      |
| hechos              | hechos_tipo_hecho_check                   | CHECK           | (((tipo_hecho)::text = ANY ((ARRAY['SUCESO'::character varying, 'ANUNCIO'::character varying, 'DECLARACION'::character varying, 'BIOGRAFIA'::character varying, 'CONCEPTO'::character varying, 'NORMATIVA'::character varying, 'EVENTO'::character varying])::text[])))                                                                                                                                          |
| hechos              | hechos_tipo_hecho_check                   | CHECK           | (((tipo_hecho)::text = ANY ((ARRAY['SUCESO'::character varying, 'ANUNCIO'::character varying, 'DECLARACION'::character varying, 'BIOGRAFIA'::character varying, 'CONCEPTO'::character varying, 'NORMATIVA'::character varying, 'EVENTO'::character varying])::text[])))                                                                                                                                          |
| hechos              | hechos_tipo_hecho_check                   | CHECK           | (((tipo_hecho)::text = ANY ((ARRAY['SUCESO'::character varying, 'ANUNCIO'::character varying, 'DECLARACION'::character varying, 'BIOGRAFIA'::character varying, 'CONCEPTO'::character varying, 'NORMATIVA'::character varying, 'EVENTO'::character varying])::text[])))                                                                                                                                          |
| hechos              | hechos_tipo_hecho_check                   | CHECK           | (((tipo_hecho)::text = ANY ((ARRAY['SUCESO'::character varying, 'ANUNCIO'::character varying, 'DECLARACION'::character varying, 'BIOGRAFIA'::character varying, 'CONCEPTO'::character varying, 'NORMATIVA'::character varying, 'EVENTO'::character varying])::text[])))                                                                                                                                          |
| hechos              | hechos_tipo_hecho_check                   | CHECK           | (((tipo_hecho)::text = ANY ((ARRAY['SUCESO'::character varying, 'ANUNCIO'::character varying, 'DECLARACION'::character varying, 'BIOGRAFIA'::character varying, 'CONCEPTO'::character varying, 'NORMATIVA'::character varying, 'EVENTO'::character varying])::text[])))                                                                                                                                          |
| hechos              | hechos_tipo_hecho_check                   | CHECK           | (((tipo_hecho)::text = ANY ((ARRAY['SUCESO'::character varying, 'ANUNCIO'::character varying, 'DECLARACION'::character varying, 'BIOGRAFIA'::character varying, 'CONCEPTO'::character varying, 'NORMATIVA'::character varying, 'EVENTO'::character varying])::text[])))                                                                                                                                          |
| hechos              | hechos_tipo_hecho_check                   | CHECK           | (((tipo_hecho)::text = ANY ((ARRAY['SUCESO'::character varying, 'ANUNCIO'::character varying, 'DECLARACION'::character varying, 'BIOGRAFIA'::character varying, 'CONCEPTO'::character varying, 'NORMATIVA'::character varying, 'EVENTO'::character varying])::text[])))                                                                                                                                          |
| hechos              | hechos_tipo_hecho_check                   | CHECK           | (((tipo_hecho)::text = ANY ((ARRAY['SUCESO'::character varying, 'ANUNCIO'::character varying, 'DECLARACION'::character varying, 'BIOGRAFIA'::character varying, 'CONCEPTO'::character varying, 'NORMATIVA'::character varying, 'EVENTO'::character varying])::text[])))                                                                                                                                          |
| hechos              | hechos_tipo_hecho_check                   | CHECK           | (((tipo_hecho)::text = ANY ((ARRAY['SUCESO'::character varying, 'ANUNCIO'::character varying, 'DECLARACION'::character varying, 'BIOGRAFIA'::character varying, 'CONCEPTO'::character varying, 'NORMATIVA'::character varying, 'EVENTO'::character varying])::text[])))                                                                                                                                          |
| hechos              | hechos_tipo_hecho_check                   | CHECK           | (((tipo_hecho)::text = ANY ((ARRAY['SUCESO'::character varying, 'ANUNCIO'::character varying, 'DECLARACION'::character varying, 'BIOGRAFIA'::character varying, 'CONCEPTO'::character varying, 'NORMATIVA'::character varying, 'EVENTO'::character varying])::text[])))                                                                                                                                          |