# docker-compose.integration.yml
# Fragmento para integrar en el docker-compose principal del proyecto
# Copiar esta sección al docker-compose.yml principal

version: '3.9'

services:
  nginx_reverse_proxy:
    build:
      context: ./nginx_reverse_proxy
      dockerfile: docker/Dockerfile
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - lamacquina_network
    depends_on:
      - module_dashboard_review_backend
      - module_dashboard_review_frontend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/usr/local/bin/health-check.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - nginx_logs:/var/log/nginx
    environment:
      - NGINX_HOST=${NGINX_HOST:-localhost}
      - NGINX_PORT=${NGINX_PORT:-80}

# Añadir a volumes existentes:
volumes:
  nginx_logs:
    driver: local

# La red lamacquina_network ya debe existir en el docker-compose principal
